name: CD

on:
  push:
    branches: [ main ]

jobs:
  build-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      - name: Build jar without tests
        run: mvn clean package -DskipTests --batch-mode

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/taskmaster:${{ github.sha }} .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Push Docker image
        run: |
          docker tag \
            ${{ secrets.DOCKER_HUB_USERNAME }}/taskmaster:${{ github.sha }} \
            ${{ secrets.DOCKER_HUB_USERNAME }}/taskmaster:latest
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/taskmaster:${{ github.sha }}
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/taskmaster:latest
